language/language/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^init/', include('init.urls', namespace='init')),
    url(r'^.*', include('main.urls')),
]

language/main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
]

language/wiki/urls.py
from django.conf.urls import url
from wiki import views

urlpatterns = [
    url(r'^$', views.wiki, name='wiki'),
    url(r'^about/', views.about, name='about'),
    url(r'^category/(?P<categoryName>[\w\-]+)/$', views.category, name='category'),
    url(r'^addCategory/$', views.addCategory, name='addCategory'),
    url(r'^addPage/(?P<categoryName>[\w\-]+)/$', views.addPage, name='addPage'),
    url(r'^deletePage/(?P<pageID>[0-9]+)/$', views.deletePage,
        name='deletePage'),
    url(r'^deleteCategory/(?P<categoryID>[0-9]+)/$', views.deleteCategory,
        name='deleteCategory'),
]

language/main/models.py
from django.db import models

# Create your models here.

language/wiki/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128, unique=True)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    

language/main/views.py
from django.shortcuts import render
import datetime

def main(request):
    context = {'message':'Django 很棒', 'time':datetime.datetime.now()}
    return render(request, 'main/main.html', context)

language/wiki/views.py
from django.shortcuts import render, redirect
from wiki.models import Category, Page
from django.core.urlresolvers import reverse
from wiki.forms import CategoryForm, PageForm

def wiki(request):
    categories = Category.objects.order_by('-likes')
    context = {'categories':categories}
    return render(request, 'wiki/wiki.html', context)

def about(request):
    return render(request, 'wiki/about.html')


def category(request, categoryName):
    context = {}
    try:
            category = Category.objects.get(name=categoryName)
            context['category'] = category
            context['pages'] = Page.objects.filter(category=category)
    except Category.DoesNotExist:
            pass
    return render(request, 'wiki/category.html', context)



def addCategory(request):
    template = 'wiki/addCategory.html'
    if request.method=='GET':
        return render(request, template, {'form':CategoryForm()})
    # request.method=='POST'
    form = CategoryForm(request.POST)
    if not form.is_valid():
        return render(request, template, {'form':form})
    form.save()
    return redirect(reverse('wiki:wiki'))
    # Or try this: return wiki(request)
    
def addPage(request, categoryName):
    template = 'wiki/addPage.html'    
    try:
        pageCategory = Category.objects.get(name=categoryName)
    except Category.DoesNotExist:
        return category(request, categoryName)
    context = {'category':pageCategory}
    if request.method=='GET':
        context['form'] = PageForm()
        return render(request, template, context)
    # request.method=='POST'
    form = PageForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, template, context)
    page = form.save(commit=False)
    page.category = pageCategory
    page.save()
    return redirect(reverse('wiki:category', args=(categoryName, )))

def deleteCategory(request, categoryID):
    if request.method!='POST':
        return wiki(request)
    # request.method=='POST':
    categoryToDelete = Category.objects.get(id=categoryID)
    if categoryToDelete:
        categoryToDelete.delete()
    return redirect(reverse('wiki:wiki'))


def deletePage(request, pageID):
    if request.method!='POST':
        return wiki(request)
    # request.method=='POST':
    pageToDelete = Page.objects.get(id=pageID)
    if pageToDelete:
        categoryName = pageToDelete.category.name
        pageToDelete.delete()
    else:
        categoryName = ''
    return redirect(reverse('wiki:category', args=(categoryName, )))
    

language/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>Django 說--Hello world!</h1>
<p>{{message}}</p>
<p>現在時間：<span style=color:red>{{time}}</span></p>
<br>
<p><a href={% url 'wiki:wiki' %}>前往 Wiki 頁面</a></p>
</body>
</html>

language/wiki/templates/wiki/wiki.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1>Wiki 說--Hello world!</h1>
{% if categories %}
    <h2>程式語言類別:</h2>
    <table>
     <tr><th>分類名稱</th><th></th></tr>
	   {% for category in categories %}
	       <tr>
                <td><a href={% url 'wiki:category' category.name %}>{{category.name}}</a></td>
           
           <td>
            <form method=post action={% url 'wiki:deleteCategory' category.id %}>
                {% csrf_token %}
                <input type=submit value=刪除>
            </form>
           </td>
           
                    
           </tr>
          	   {% endfor %}
	</table>
{% else %}
	<p><strong>目前尚未設定程式語言類別。</strong></p>
{% endif %}
<br>
<p><a href={% url 'wiki:addCategory' %}>新增類別</a></p>
<p><a href={% url 'main:main' %}>回首頁</a></p>
</body>
</html>